### ISSUE TITLE
Incorrect color values?

### ISSUE THREAD

**Issue by drw158** [cssstats/cssstats#104]
When I paste this css into the Raw CSS field, it returns "5 unique colors".

CSS: https://cloudup.com/cE_f4A-bXyW

I scrolled down to the Raw CSS output and saw at least 2 other colors that weren't included in the Colors section.

**Comment by johnotander** [comment]
I believe this is no longer an issue, I've also created a PR on jxnblk/css-statistics#11 that verifies it has been resolved.

**Comment by mrmrs** [comment]
Fixed on production after latest deploy.
Thanks again @nene - appreciate you isolating the problem code.
