### ISSUE TITLE
Stops reading assessing file after selector

### ISSUE THREAD

**Issue by chryton** [cssstats/cssstats#116]
Apparently after the `form .links ul li,` selector string below, the file is no longer assessed but is apparently completely read. Preceding these is a data image/png wrapped in a media query, if that is helpful. I can give you a larger portion of the file if necessary.

`a.button,a.button:visited,input.button,span.button{display:block;font-size:13px;font-size:1.3rem;color:#d5d3c8;background-color:#4d4d4d;border:0;text-decoration:none;text-transform:uppercase;text-align:center;padding:6px;padding:.6rem;margin-bottom:10px;margin-bottom:1rem;line-height:inherit}form .links ul li,form ul li label,form ul li.required-text span{font-family:"Trade Gothic Bold",Arial,Helvetica,sans-serif;color:#999;font-size:11px;font-size:1.1rem;text-transform:uppercase;padding-bottom:2px;padding-bottom:.2rem}`

**Comment by chryton** [comment]
Has there been any insight as to what the issue is?

**Comment by johno** [comment]
This should be fixed in the latest version!
