### ISSUE TITLE
URLS that don't currently work

### ISSUE THREAD

**Issue by mrmrs** [cssstats/cssstats#128]
The following sites all return this error:

`TypeError: Cannot read property 'length' of undefined`

In an effort to consolidate tickets and reduce noise I'll move any new issues for any  URI that fails here. 
- [x] http://stripe.com
- [x] http://alistapart.com
- [ ] http://thegrid.io

**Comment by hoffi** [comment]
Stripe works

**Comment by mattbrundage** [comment]
Here's one more that doesn't work: http://www.faa.gov/
The direct link to the CSS file returns the same error: http://www.faa.gov/templates/4/assets/css/main.css

**Error: getaddrinfo ENOTFOUND faa.gov**

I know for a fact that the domain faa.gov **requires** the "www" subdomain, and will not resolve properly without it. I am embarrassed for whoever set up their DNS.

Ensure that CSSStats is not stripping the "www" subdomain from URLs before it's passed to getaddrinfo()

**Comment by huskycdn** [comment]
I get this error:
`TypeError: Cannot read property 'specificity' of undefined`
on this site (and directly linked CSS file):
http://www.louisebay.com

I get this error:
`TypeError: Cannot read property '0' of undefined`
on this site (and directly linked CSS file):
http://test-mrt.dreamhosters.com (this won't be around long)

**Comment by alibby251** [comment]
I get this error when referencing a site hosted on localhost:

```
TypeError: Cannot read property 'length' of undefined 
```
The weird thing is that I've had it working locally, as I have a screenshot taken at the time - trouble is, I can't figure out what's broken it since...I'm assuming that it should work on localhost, right? I only ask as the documentation doesn't specify that it doesn't support localhost ;-)

**Comment by chharvey** [comment]
@alibby251 I'm getting the same error when referencing a css file hosted on [cdn.rawgit.com](https://rawgit.com/) as well as (non-cdn) rawgit.com

**Comment by sparanoid** [comment]
I got the same error on my personal site: http://sparanoid.com/

> TypeError: Cannot read property 'length' of undefined

**Comment by sergigallent-tui** [comment]
Same error when uploading a css file from dropbox public folder:
`TypeError: Cannot read property 'length' of undefined `

**Comment by stof** [comment]
I got similar errors when using direct CSS URLs which included some query string (for cache busting purpose). Removing the query string from the URL made it work.

So maybe all websites reported as breaking above with this `TypeError: Cannot read property 'length' of undefined` message are websites using query-string-based cache busting on CSS URLs.
