### ISSUE TITLE
Stylesheet size (in KB) is a bit off

### ISSUE THREAD

**Issue by joaocunha** [cssstats/cssstats#129]
The total size is showing a value a tad bit smaller than the actual file size.

The attached stylesheet has **190993 bytes**, although CSS Stats reports **187 KB**.

- [Raw stylesheet](https://flassets.a.ssl.fastly.net/stylesheets/base_packaged.css?v57d62e737cdfcb)
- [CSS Stats report](http://cssstats.com/stats?link=https%3A%2F%2Fflassets.a.ssl.fastly.net%2Fstylesheets%2Fbase_packaged.css%3Fv57d62e737cdfcb)

**Comment by jxnblk** [comment]
We currently use [Humanize](https://github.com/HubSpot/humanize) for file sizes, but even checking http://filesizejs.com/ seems to produce the same results. What value are you expecting to see?

**Comment by jxnblk** [comment]
Closing this for now since this seems accurate, but please reopen if not.

**Comment by hoffi** [comment]
Humanize is rounding up the file size since the real size (190993 bytes) is 186.51 KB exactly. 
But with rounding it is 187 KB.
