### ISSUE TITLE
CSS import is included twice in stats

### ISSUE THREAD

**Issue by vlad-saling** [cssstats/cssstats#130]
I've noticed that if page uses @imports in CSS the imported file gets to be included twice in statistics.

You can test it from here: http://import.meetpollux.com/
Result: http://cssstats.com/stats?url=http://import.meetpollux.com/

See the content of imported style1.css file: 
body {
    color: black;
}

Maybe the content is included once as "part" of original CSS request and then second time as standalone file request detected from the code?

**Comment by johnotander** [comment]
Thanks for reporting this! I will do a bit of digging to see what's happening here.

**Comment by johnotander** [comment]
This is now resolved in the `get-css@1.0.1`. Now, cssstats just needs a redeploy with:

```
npm cache clean
npm i get-css@latest --save
```

To ensure the latest version of `get-css` is installed. cc/ @mrmrs

**Comment by mrmrs** [comment]
Will this up when I get home and have access to my non-work cpu machine.

**Comment by mrmrs** [comment]
Fixed on production.
