### ISSUE TITLE
Specificity Graph

### ISSUE THREAD

**Issue by istref** [cssstats/cssstats#131]
Hi 
Can someone look at my Specificity graph and tell me is it bad or worse.
http://postimg.org/image/jyc5y3xhj/

Is there any information on how to make it better.

**Comment by johnotander** [comment]
Harry Roberts [states](http://csswizardry.com/2014/10/the-specificity-graph/) the best specificity graph is an upward trend. The linked article should provide more context. In brief, you can achieve this trend by placing the more specific selectors at the end of your stylesheet.
