### ISSUE TITLE
Doesn't resolve relative urls to css from .html files

### ISSUE THREAD

**Issue by dethe** [cssstats/cssstats#133]
A relative URL referenced inside a file ending with .html (as opposed to a service or an implied index.html that ends with /) should be relative to the containing folder, not to the .html file itself. For instance, loading the url `http://waterbearlang.com/playground.html` tries to resolve `css/reset.css` as `http://waterbearlang.com/playground.html/css/reset.css` instead of the correct `http://waterbearlang.com/css/reset.css`.

**Comment by mrmrs** [comment]
Fixed on production. Thanks for calling this to our attention @dethe

**Comment by dethe** [comment]
Awesome, thanks! This is a great project and looks super-helpful, especially when I'm mentoring students who are new to the waterbear project.
