### ISSUE TITLE
Specificity error

### ISSUE THREAD

**Issue by intel352** [cssstats/cssstats#134]
http://cssstats.com/stats?url=http%3A%2F%2Fwww.quiksilver.com

Returns:

`TypeError: Cannot read property 'specificity' of undefined`

I also tried our main CSS file directly, same error. Thoughts?

**Comment by kamranayub** [comment]
Also encountered for: http://cf.geekdo-static.com/static/css_master2_5500d52d523a2.css

**Comment by Quelu** [comment]
Any solutions for this bug ?

**Comment by pagestyles** [comment]
Same here

**Comment by lachlanjc** [comment]
@intel352 Seems to be working (locally, the server is down). Not sure what fixed it though 😜

**Comment by johnotander** [comment]
Closing as these urls no longer cause errors.
