### ISSUE TITLE
Add direct input method to allow users to enter the CSS they would like analyzed

### ISSUE THREAD

**Issue by bjankord** [cssstats/cssstats#153]
I have a project I'd like to run through cssstats, especially to see all the graphs, though it is only available on a private network. 

It would be helpful if I could paste my raw css into a textarea for the CSS to be analyzed.

Edit: Ah, I found running the app locally has this feature. Logged https://github.com/cssstats/cssstats/issues/154 about error I ran into with Raw CSS.

**Comment by jxnblk** [comment]
Yes we used to have this feature on the public site as well, but it wasn't working properly. Would love to have this back, but my understanding of how to properly handle that is limited.
