### ISSUE TITLE
CSS Stats pulls SVG titles 

### ISSUE THREAD

**Issue by augbog** [cssstats/cssstats#159]
When supplying a website, CSS Stats will show at the top whatever is supplied in the `<title>` tag. However, it seems that it doesn't discern where that `<title>` tag is. SVGs have their own [`<title>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title) tag so sometimes it will pull those.

Ideally CSS Stats should only pull the `<title>` tag that is within the `<head>`.

And example is this website https://invisionapp.com/do 

![screen shot 2015-06-04 at 1 39 23 pm](https://cloud.githubusercontent.com/assets/2054339/7994037/2e3a7f62-0abf-11e5-85c4-06e20efca4ab.png)

**Comment by johnotander** [comment]
Thanks for reporting! This is definitely a bug.

**Comment by augbog** [comment]
This is fixed now! Thanks for merging my change in! Closing.
