### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by wesort** [cssstats/cssstats#166]
Hi,

I'm a huge fan of this project. So useful and beautifully done.  

Not been able to connect to the site recently though and have tied a couple of times over the last week or so?? http://downforeveryoneorjustme.com/http://cssstats.com

Thanks.

**Comment by mrmrs** [comment]
Hi @wesort We are currently aware the site is down. We are in the midst of trying to fix it ourselves but have failed at the dev ops stuff. We are currently trying to find corporate sponsors that will help us financially so we can hire the needed resources to give us a more stable solution. Thanks for letting us know though.

**Comment by wesort** [comment]
Fair enough. I figured you knew of course.

If you decide to crowd fund it I'd certainly put some money in the hat. I'd prefer to do that over a monthly subscription model as it would be another receipt & payment to account for each month.

**Comment by mrmrs** [comment]
@wesort - ha thanks. Well you'll be happy to know we are back up and running at the moment :)
