### ISSUE TITLE
GZIP Issue

### ISSUE THREAD

**Issue by andres-torres-marroquin** [cssstats/cssstats#178]
It looks like it fails with some GZIP hosted files, see the Raw CSS

http://cssstats.com/stats?link=https%3A%2F%2Fbuckets-staging.s3.amazonaws.com%2Fstyles%2Fprod%2Fmain.f4679621e8d5.css

Original file is hosted here: https://buckets-staging.s3.amazonaws.com/styles/prod/main.f4679621e8d5.css

**Comment by johnotander** [comment]
Thanks for reporting!

It looks like we currently have a bit of a bug when it comes to CSS links in the app. Changing the url to http://cssstats.com/stats?url=https%3A%2F%2Fbuckets-staging.s3.amazonaws.com%2Fstyles%2Fprod%2Fmain.f4679621e8d5.css (`s/link/url/`) will work for now as a temporary work around. I'll work on getting a fix in for this bug sometime this week.

**Comment by andres-torres-marroquin** [comment]
I have just figured the same you just wrote!

Thanks for this great project. seeing the code it looks like it's maybe related to the `request` library
