### ISSUE TITLE
CSSStats is not running at all

### ISSUE THREAD

**Issue by lachlanjc** [cssstats/cssstats#179]
On every page, the server can't find the layout :cry:

[cssstats.com](http://cssstats.com)

```
Error: ENOENT: no such file or directory, open '/var/www/views/layouts/application.handlebars'
   at Error (native)
```

**Comment by johnotander** [comment]
Whoopsies :blush:. I botched a deploy. It should be up and running now. Let us know if you encounter any issues.

**Comment by lachlanjc** [comment]
Awesome. Thanks @johnotander!
