### ISSUE TITLE
`inherit` is seen as a named colour/font size

### ISSUE THREAD

**Issue by marijnvdwerf** [cssstats/cssstats#184]
Can be seen on <http://cssstats.com/stats?link=https%3A%2F%2Fblendle.com%2Fcss%2Fstyle.css>

**Comment by younes-14** [comment]
https://www.youtube.com/watch?v=SJgYdTckMBY

**Comment by johnotander** [comment]
I believe this is desired behavior because it illustrates a value for a font color/size declaration. Soon, we will be also adding a count for the number of times a value is declared for a given property so this will be even more enlightening. Thanks for creating this issue!
