### ISSUE TITLE
Issue with HTTPS

### ISSUE THREAD

**Issue by ccorcos** [cssstats/cssstats#186]
When I use `https://www.affirm.com/u/#/signin`, it shows me stats for both the vendor stylesheet and the main stylesheet. When I inspect element and use only the main stylesheet `https://d11bn9i8gmo4kr.cloudfront.net/products/user_portal/master/dist/styles/8aec3e44.main.css`, I get a bunch of gibberish in the raw css pane.

![image](https://cloud.githubusercontent.com/assets/1794527/12563200/f44a3754-c35d-11e5-825c-18ef1e0c4583.png)

**Comment by johno** [comment]
Looks like this is no longer an issue, thanks for reporting!
