### ISSUE TITLE
Provide the ability to specify a user agent

### ISSUE THREAD

**Issue by rmurphey** [cssstats/cssstats#194]
For better or for worse, our mobile application sends a different payload for different user agents (mostly to provide a fast experience to feature phones vs. smart phones). CSSStats by default seems to provide the user agent `Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36`, which isn't recognized as a mobile UA. 

I'd like to propose an enhancement that would add a user agent dropdown to the tool's interface. If this is something you'd be open to, I can probably put together a pull request.

**Comment by kevinwuhoo** [comment]
This seems to be a dupe of #145 and is partially implemented in #156 for a few mobile UAs.

**Comment by rmurphey** [comment]
Ah sorry -- I tried to look at the existing issues but clearly didn't do a very good job.

**Comment by johnotander** [comment]
Thanks for opening the issue @rmurphey! We will try to incorporate that functionality sometime soon, and please do open more issues for any bugs you find or other features you'd like to see added :smile_cat:

**Comment by kevinwuhoo** [comment]
@rmurphey sorry if I seemed overly terse! Was in a hurry because my laptop to die, didn't mean to be rude.

**Comment by rmurphey** [comment]
@kevinwuhoo not at all, still not sure how I missed an issue so clearly titled!
