### ISSUE TITLE
Support for inline <style>

### ISSUE THREAD

**Issue by lachlanjc** [cssstats/cssstats#203]
Some websites, such as [Marvel](https://marvelapp.com/styleguide/), are switching to inlining CSS with a `<style>` tag instead of making another HTTP request. It’d be awesome if cssstats could handle that 😀

**Comment by lachlanjc** [comment]
(or, if we could just paste CSS in directly)

**Comment by chharvey** [comment]
or if you could paste the url to a direct CSS file (e.g. `http://example.com/styles/site.css`)

**Comment by mrmrs** [comment]
@lachlanjc CssStats does handle that... let me know if there are links that are not working. But that's definitely something that is working on my end.

@chharvey - You can paste the url to a direct css file currently.

**Comment by lachlanjc** [comment]
@mrmrs https://marvelapp.com/styleguide/ 😬

**Comment by mrmrs** [comment]
That error isn't due to the style tag.
