### ISSUE TITLE
Use a headless browser for get-css

### ISSUE THREAD

**Issue by johno** [cssstats/cssstats#204]
As SPAs become more popular we should be able to execute javascript in order to boot webpacked apps so that we can then get the CSS added to the page after app boot.

**Comment by bartveneman** [comment]
Example implementation: 

repo: https://github.com/bartveneman/extract-css
live demo: https://extract-css.now.sh/

**Comment by johno** [comment]
Thanks for the data @bartveneman! Now that SSR (thankfully) is becoming commonplace I'm going to opt to avoid a browser runtime to keep down the server bills. If folks need a runtime they can use your lib! 💟
