### ISSUE TITLE
Microsoft filter-based gradients break the css parser

### ISSUE THREAD

**Issue by pixelbandito** [cssstats/cssstats#205]
IE's old filter gradients break the css parser, producing the message: `TypeError: Cannot read property 'length' of undefined`

I tested with:
- Gist: https://gist.github.com/pixelbandito/fd0b3b3415d9f09b61bd322211bad011
- Raw version: https://gist.githubusercontent.com/pixelbandito/fd0b3b3415d9f09b61bd322211bad011/raw/f00829a55cca8a801f6d5761267849ba24b5b207/gradient-ms-filter.css

I know this filter syntax is non-standard, and I want to get rid of it. Making cssstats understand it would be helpful, though I understand it might be outside the project's intended scope.

**Comment by johno** [comment]
This is fixed in latest versions.
