### ISSUE TITLE
Download results

### ISSUE THREAD

**Issue by lachlanjc** [cssstats/cssstats#206]
It’d be awesome to download a PDF/file of the results, esp. so you could save the stats before a major refactoring or event.

**Comment by mrmrs** [comment]
You can download to pdf now as print > save to pdf.

Saving stats server side will be an issue we tackle with the upcoming paid / pro version though so people can share links. 

Let me know if you meant something different.

**Comment by sara-jean** [comment]
I'd love to have a download option (JSON?) so that I can compare my stats over time. These metrics can help show progress of a refactor.

**Comment by mrmrs** [comment]
@sara-jean - yes the pro version we are currently working on will allow you to track changes over time :) Otherwise, if you're comfortable with javascript at all and don't want to wait, you can use the css stats core module to generate json yourself:

https://github.com/cssstats/core
