### ISSUE TITLE
Cannot read property length of undefined

### ISSUE THREAD

**Issue by Lindsor** [cssstats/cssstats#208]
Hey guys,

first of all great job love the tool, not sure if this is the place to put this but it fails when i use my stylesheet:

http://marceloluz.com/styles/main.css

the error is "Cannot read property length of undefined"

Thank you,

great job again

**Comment by CheungJ** [comment]
I'm seeing the same error when running cssstat locally via the `npm start` command.

**Comment by johnotander** [comment]
Hey all, looks like you found a small bug in our parser. I've patched the app and redeployed so everything should be working again. Let me know if you encounter any more problems.

Thanks for reporting!
