### ISSUE TITLE
cssstats.com is down

### ISSUE THREAD

**Issue by lachlanjc** [cssstats/cssstats#209]
⚠️ The website is down, and isup.me is confirming that. cc @jxnblk @johnotander @mrmrs 

https://cssstats.com/

**Comment by htor** [comment]
Please make it live again, because it's awesome!

**Comment by johnotander** [comment]
It's back up again. My apologies, was away on vacation so I didn't have compute access to give the server a kick.

**Comment by htor** [comment]
Still down it seems.

**Comment by lachlanjc** [comment]
@johnotander Yo that’s fine! Thanks for fixing. :+1:

Have you checked out [Panic](https://panic.com)’s Prompt/Coda 2? It allows you to SSH and edit files from your iPhone/iPad :wink:

**Comment by acz13** [comment]
huh? 25 bucks for a remote file editor...

you're joking... right?

**Comment by AleksejDix** [comment]
website is down again

**Comment by raphaelgoetter** [comment]
:(
