### ISSUE TITLE
Order colors

### ISSUE THREAD

**Issue by acz13** [cssstats/cssstats#211]
I always thought ordering colors the way we have it now is a bit too random...

perhaps someone could come up with a way to sort it into blues, greens, reds, yellows, etc.? just throwing the idea out there

**Comment by jxnblk** [comment]
I think sorting by source order makes a lot of sense, for any of the properties shown. If they appear random, that's the stylesheet author's fault, right?

**Comment by mrmrs** [comment]
@acz13 Yes our intention is to visualize what is occurring within the css file so reordering the colors would dilute the quality of the presented information. The colors aren't ordered randomly - they are presented in the exact order the authors have declared them. In the next version of css stats I think we'll have views for both visualizing css but also living style guide stuff as well so there might be a toggle or alternate view in the future.
