### ISSUE TITLE
Unable to run npm start

### ISSUE THREAD

**Issue by philllip** [cssstats/cssstats#216]
Hi
Sorry if this is the incorrect place to post this but I'm having issues running "npm start" after successful installing cssstats. Please see attached error message below:

`> rprtr@1.0.0 start /Users/philipardeljan/src/cssstats
> node ./bin/www

/Users/philipardeljan/src/cssstats/controllers/stats.js:16
  for(var property of totalProperties) {
                   ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/philipardeljan/src/cssstats/routes/stats.js:6:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! rprtr@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the rprtr@1.0.0 start script.
npm ERR! This is most likely a problem with the rprtr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls rprtr
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.5.0
npm ERR! command "/opt/nodes/0.10.38/bin/node" "/opt/boxen/nodenv/versions/0.10.38/bin/npm" "start"
npm ERR! cwd /Users/philipardeljan/src/cssstats
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/philipardeljan/src/cssstats/npm-debug.log
npm ERR! not ok code 0
`

![error](https://cloud.githubusercontent.com/assets/13126574/17426575/a615cc4a-5b1c-11e6-9609-06343b081575.png)

**Comment by johnotander** [comment]
This is the right place : ). It appears that your node version is pretty out of date which is causing the errors. I'd recommend using node version 4+ to run the app. If you need to manage multiple node versions you can use a version manager like [rvm](https://github.com/creationix/nvm).

**Comment by saalmaan** [comment]
Can confirm its working on node 6+

**Comment by philllip** [comment]
Can't get around to updating node just yet, will re-open when I get around to it.
