### ISSUE TITLE
Broken on https://www.carphonewarehouse.com

### ISSUE THREAD

**Issue by saalmaan** [cssstats/cssstats#217]
Hello, 
Thank you for the Awesome tool. 
Its not working on following URLs

```
https://www.carphonewarehouse.com
https://www.carphonewarehouse.com/apple/iphone-6s.html
https://www.carphonewarehouse.com/etc/designs/ews/mastercsslibs.min.03ff431b0049b10e7fdc32fafbe77bf1.css
https://www.carphonewarehouse.com/etc/designs/ews/pdp.min.f8a7be9063625a8ce9042762c6e091f9.css
```

uncompressed CSS URLS

```
https://www.carphonewarehouse.com/etc/designs/ews/mastercsslibs.03ff431b0049b10e7fdc32fafbe77bf1.css
https://www.carphonewarehouse.com/etc/designs/ews/pdp.f8a7be9063625a8ce9042762c6e091f9.css
```

**Comment by mrmrs** [comment]
Hi @saalmaan,

Unfortunately the site needs valid css to give you stats. Looks like you have a number of syntax errors in your css. If you fix those, you should be able to get stats.

https://jigsaw.w3.org/css-validator/validator?uri=www.carphonewarehouse.com&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en
