### ISSUE TITLE
website is down again!

### ISSUE THREAD

**Issue by AleksejDix** [cssstats/cssstats#234]
pls can you check what has happend

**Comment by johnotander** [comment]
Gave the server a kick, should be happy again 😃 . Thanks for letting us know. Hopefully next week I will be able to move the instance over to something more stable.

**Comment by johnotander** [comment]
Looks like we're being repeatedly hit by a request that causes the app to crash, will look into fixing it shortly. Got a few things on my plate this morning.

**Comment by digitalfabric92** [comment]
Hey, the site is still down. Anything we can do to help put it back up again?

**Comment by johnotander** [comment]
My apologies, I forgot to get back to this. It's now live again.
