### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by mmorrison22** [cssstats/cssstats#238]
Trying to access - http://cssstats.com/ gives an error "Refused to connect" ERR_CONNECTION_REFUSED

**Comment by Andersos** [comment]
Loads fine for me. http://cssstats.com works but https://cssstats.com gives me the error you described

**Comment by opsvetica** [comment]
I am getting the same "refused to connect" issue.

**Comment by RodrigoRMG** [comment]
same problem here

**Comment by johnotander** [comment]
Yeah, apologies, the server has been a bit flaky lately. When we get #236 merged in we will be switching over to Zeit's Now and things will hopefully get more stable again.

**Comment by misterhtmlcss** [comment]
@johnotander any news? Just tried https/http and in Chrome and Safari and I got nada.

**Comment by johno** [comment]
App is now swung to ZEIT's Now (and as a result much stabler), please let me know if you encounter any issues.
