### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by cipionhabla** [cssstats/cssstats#241]
Trying to access - http://cssstats.com/ gives an error

This site can’t provide a secure connection
www.cssstats.com sent an invalid response.
Try running Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

**Comment by johno** [comment]
Thanks for opening up this issue! We're in the midst of swinging DNS, so availability will be intermittent for a little while. For the time being you can access the app at: https://cssstats-app.now.sh/

Thanks for your patience 💟

**Comment by johno** [comment]
Everything should be swung now, let us know if you encounter any other issues!

**Comment by ClemMakesApps** [comment]
I also deployed to https://css-stats.glitch.me/ in case someone needed an alternative link
