### ISSUE TITLE
Where are these stats coming from?

### ISSUE THREAD

**Issue by mascardoso** [cssstats/cssstats#243]
Hi is there a way to understand from which lines of code are these stats coming from? So for instance if we detect that there's a `font-size:80px` where could we see that this is coming from? 

Thanks

**Comment by bartveneman** [comment]
The bottom of the page usually shows the sources of the CSS, like style.css, or some inline block: https://cssstats.com/stats?url=https%3A%2F%2Fwww.facebook.com&ua=Browser%20Default#raw-css

You can ctrl+F you way through that to find the exact value you're looking. Note that it's possible that this a value that is generated by 3rd party CSS or your preprocessor (`$font-size * 2`).

**Comment by johno** [comment]
Thanks for chiming in @bartveneman! As he states, for now it's a bit of command+f searching in the output CSS. In the future we may add the ability to drill down into exact locations a given declaration is found.
