### ISSUE TITLE
Any thought on releasing this as NPM Package?

### ISSUE THREAD

**Issue by Nikodermus** [cssstats/cssstats#247]
I'm working for a  VPN restricted company and I want to do some styleguides and show how style is currently being managed, I think this is a great tool and would be awesome to be used as part of a project to showcase these glorious stats, have you thought on releasing it as a module which can generate a report? If so, I'd be interested in helping you guys

Thanks for the awesome job

**Comment by jxnblk** [comment]
See https://www.npmjs.com/package/cssstats
