### ISSUE TITLE
How to visualize the results.json?

### ISSUE THREAD

**Issue by justlevine** [cssstats/cssstats#255]
How can i view the reports json for a localhost analysis like on cssstats.com?

**Comment by SuneRadich** [comment]
I am also looking for a way to just visualize the results. Basically I want to do something similar to [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) where I from the CLI can run a command, and have a webserver started that displays the stats.

The way I understand cssstats, the overall package is the service also found on cssstats.com - ie. something where you input an url, and then display stats.

I just want to generate the stats on the fly (in a build step), and then based on the output from the [cssstats npm package ](https://github.com/cssstats/cssstats/tree/master/packages/cssstats) show the stats.

**Comment by bartveneman** [comment]
@justlevine You could use https://github.com/bartveneman/wallace-cli (disclaimer: I made this), https://github.com/t32k/stylestats or  https://github.com/katiefenn/parker for a more graphical output of the css stats (they all use different stats generators though, beware).

@SuneRadich If you want to store your stats for a more historical analysis, try projectwallace.com (disclaimer: I made this). You could send your CSS in a build step, get the results back in JSON and view the results like this: https://www.projectwallace.com/~teamwallace/project-wallace/
