### ISSUE TITLE
Submititng URLs That Begin with https:// or http:// Crash the Site and Fail to Render

### ISSUE THREAD

**Issue by kingkool68** [cssstats/cssstats#279]
If you submit a link that starts with `https://` https://cssstats.com crashes. `https://whatever` gets reduced to `https:/whatever` in the URL query parameter and the API then returns a 500 and nothing is rendered. 

Pasting a URL with no http(s):// in front seems to work just fine.

Example: Entering `https://google.com` results in this URL https://cssstats.com/stats?url=https:/google.com which doesn't work. Entering `google.com` results in this URL that does work https://cssstats.com/stats?url=google.com 

Maybe consider stripping `https://` and `http://` from `url` before navigating to the stats URL in https://github.com/cssstats/cssstats/blob/9b1319c476f5d24a64db38426677450d46eb8aac/src/components/UrlForm.js#L15

**Comment by johno** [comment]
Thanks for opening up such a thorough issue report! A fix is deploying now.
