### ISSUE TITLE
 ERROR #98123  WEBPACK

### ISSUE THREAD

**Issue by vetras** [cssstats/cssstats#286]
Hi all,
I'm almost sure this is my problem but i don't understand why.

I've followed the readme instructions on how to get the project running:

```
git clone master ...
yarn
yarn start
```

...
i get 8 warnings about un-used vars, then this:

```
ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'css-unit-sort' in ' (path to) /cssstats/src/components'

File: src/components/FontSizes.js

failed Building development bundle - 7.269s
```

Although not on the readme, I've installed globally `gatsby` `webpack` and `yarn` with `npm`.
What am I missing?

**other info:**
* macos 10.15.1
* node v11.14.0
* yarn 1.19.1
* npm 6.7.0
* gatsby 2.17.7 (cli 2.8.8)
* webpack 4.41.2

**Comment by vetras** [comment]
`npm i -S css-unit-sort`
`yarn start`
on the project root solved the issue.

Should this be on the readme ?

**Comment by johno** [comment]
This should now be fixed, thanks for opening up an issue!
