### ISSUE TITLE
Specificity graph not visible in dark mode

### ISSUE THREAD

**Issue by JonathanTroyer** [cssstats/cssstats#287]
### Light theme
![image](https://user-images.githubusercontent.com/15098499/68172297-a140a600-ff3c-11e9-8c34-61fcef51cb37.png)

### Dark theme
![image](https://user-images.githubusercontent.com/15098499/68172300-a43b9680-ff3c-11e9-8f34-9164a46da363.png)

I'm testing with [Bootstrap](https://cssstats.com/stats/?url=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Ftwitter-bootstrap%2F4.3.1%2Fcss%2Fbootstrap.min.css)

**Comment by mountainash** [comment]
Also the "Ruleset Size" graph.

**Comment by lachlanjc** [comment]
This has since been fixed! @johno 
<img width="660" alt="image" src="https://user-images.githubusercontent.com/5074763/101561463-660c7400-3993-11eb-9434-ce023d6f61d0.png">
