### ISSUE TITLE
`/stats` endpoint is accessible and shows infinite loading

### ISSUE THREAD

**Issue by florenceshelley** [cssstats/cssstats#295]
## Summary

User is able to navigate to `https://cssstats.com/stats/`, where it gives the perception that the page is waiting for a request to be completed, despite that not being the case

## Reproduction Steps

* From the home page, query for any site
* After being redirected to the `/stats?url={url}` endpoint, remove the query params and navigate directly to `/stats`
* Observe the loading indicator with text "Downloading and analyzing CSS from"

## Comments

This could maybe redirect the user to a 404 page or back to the home page instead

## Screenshots

![Screenshot 2020-07-02 at 1 53 33 PM](https://user-images.githubusercontent.com/23623312/86394714-fddf9680-bc6c-11ea-84c4-89235bde82d0.png)

**Comment by huldan** [comment]
me too

**Comment by huldan** [comment]
I cant analyze ibid.astra.co.id
