### ISSUE TITLE
No longer maintained?

### ISSUE THREAD

**Issue by willster277** [cssstats/cssstats#343]
Is this repo still being maintained?

Many of the dependencies are deprecated (17 deprecation warnings, 15 others), and theres a distinct lack of error handling for a url that could not be retrieved, as well as many valid URLs simply not being retrieved despite being otherwise accessible to the app. On top of this, cloning the repo, installing dependencies, and running the start command results in `TypeError: Cannot set property 'esSyntax' of undefined` and exits with status 1.

I've seen some of these problems asked about in issues, but it seems like nothing has happened for a few months now.
Is this repo still being maintained?

**Comment by johno** [comment]
We maintain this project as time permits, but most of us are pretty busy with other things.

We'd happily accept PRs for fixing the dev build, missing error handling, dependency updates, or new functionality. In fact we'd love that, and can help guide folks as they navigate what's needed for those contributions.

Regarding the local dev start issue, I'm guessing it's something to do with the out of date version of Gatsby.

**Comment by mrmrs** [comment]
Going to close this as the question has been answered
