### ISSUE TITLE
Format of Specificity Scores

### ISSUE THREAD

**Issue by thierryk** [cssstats/cssstats#68]
In my opinion, Specificity Scores should be formatted **differently**. May be using a comma (1,3,0) or a dash (1-3-0) to separate the integers (130). 

This should help people better understand those scores and prevent issues with selectors like these:

100 for #foo {...}
100 for .bar-1 .bar-2 .bar-3 .bar-4 .bar-5 .bar-6 .bar-7 .bar-8 .bar-9 .bar-10 {...} 

I think 1,0,0 and 0,10,0 would make more sense.

**Comment by jon-nunan** [comment]
From reading the spec: https://www.w3.org/TR/CSS2/cascade.html#specificity thierryk seems right to me?

**Comment by thierryk** [comment]
Yes, values are additive **within the scope of each letters** (a, b, c, d)&mdash;see link in @jon-nunan's comment. 

Saying "Base 10 specificity score" does not really make sense...

**Comment by jxnblk** [comment]
I remember asking Harry Roberts about the specificity graph when he first wrote his article and not getting a very clear answer on how to actually graph it out. (i.e. 0,0,0,12 is lower than 0,0,1,0) The base 10 math is a compromise for graphing purposes. I think we could still show the actual values somewhere, but I can't think of a better way to graph them.
