### ISSUE TITLE
Bypassing Basic Auth

### ISSUE THREAD

**Issue by jonleesmith** [cssstats/cssstats#72]
Great tool guys! 
Is there a plan of passing basic auth on sites to run the stats on?
i.e - W3 Validator popus up the basic auth window when you enter the url. 
http://roythornes.conscious.co.uk is an example - which is an internal test site

**Comment by johno** [comment]
This isn't something we'll add to the roadmap right now, but we will soon add the ability to cut and paste CSS in order to get stats so you can follow along with that issue #250
