### ISSUE TITLE
Media-queries in em

### ISSUE THREAD

**Issue by nico3333fr** [cssstats/cssstats#76]
Hello,

Just to notify a micro-bug : for this example http://www.cssstats.com/stats?url=http%3A%2F%2Frocssti.net%2F
it says that I've made some MQ maxWidth:55625em => the dot is missing : 55.625 em ;)

Kind regards and thanks btw for this tool,
Nicolas

**Comment by johnotander** [comment]
Thanks for reporting! This bug will be addressed in #102, and we'll hopefully have a fix in soon.
